#!/bin/sh
# Shared entrypoint for buildout-era Plone images (3.1+).
#
# The tarball-era entrypoint cannot be reused: a buildout instance keeps
# zope.conf and inituser under parts/instance/ (both GENERATED by
# plone.recipe.zope2instance), and is run through bin/instance rather than
# bin/runzope.
#
# Expects: $INSTANCE_HOME, $ZOPE_HTTP_PORT (default 8080)
set -e

ZOPE_HTTP_PORT="${ZOPE_HTTP_PORT:-8080}"
CONF="${INSTANCE_HOME}/parts/instance/etc/zope.conf"
INITUSER="${INSTANCE_HOME}/parts/instance/inituser"

# /data is a volume AND it is the instance's var/ -- the whole directory is a
# symlink to it, the same shape plone/plone-backend uses ([V 2026-08-21]:
# `/app/var -> /data`, with blobstorage, cache, filestorage and logs inside).
#
# So this has to recreate the ENTIRE var layout, not just the storage: nothing
# baked into /data at build time survives a bind mount, and a missing directory
# here is a startup failure rather than a silent one.
#
#   filestorage/    the ZODB
#   log/            event and access logs
#   blobstorage/    4.0+ only -- zope.conf grows a blob-dir there
#   instance/       CLIENTHOME; zdaemon's socket, and import/
#   backups/        3.x only -- collective.recipe.backup
#
# The union is created unconditionally: an unused directory costs nothing,
# whereas branching on the era would put a version check in the one place that
# is meant not to have any.
mkdir -p /data/filestorage /data/log /data/blobstorage /data/instance/import \
    /data/backups /data/snapshotbackups

# -demo images only: install the pre-built database on first start.
#
# The site is created at BUILD time and the resulting Data.fs is baked in at
# /app/seed/Data.fs — it cannot be baked at /data, because /data is a VOLUME
# and anything a later layer writes there is discarded. Seeding here, before
# the inituser block below, is what makes that block correctly skip itself:
# the seeded database already carries its admin user.
#
# Base images have no /app/seed, so this is a no-op for them.
# The ZEO_ADDRESS guard is not tidiness: under ZEO the storage is remote, so a
# seeded /data/filestorage/Data.fs is never opened, and the reset-admin-password
# step below would then be applied to the WRONG database.
if [ -n "${ZEO_ADDRESS:-}" ] && [ -f /app/seed/Data.fs ]; then
    echo "ZEO_ADDRESS is set: not seeding the demo database (the storage is remote)" >&2
fi
if [ -z "${ZEO_ADDRESS:-}" ] && [ ! -f /data/filestorage/Data.fs ] && [ -f /app/seed/Data.fs ]; then
    echo "seeding /data/filestorage/Data.fs from the demo database"
    cp /app/seed/Data.fs /data/filestorage/Data.fs
    # [V 2026-08-20] The leftover inituser MUST go, and this is not tidiness.
    # Zope applies inituser whenever the file exists — it does NOT check first
    # whether the database already has users — and then deletes it. A -demo
    # image inherits the base image's placeholder inituser, so without this the
    # seeded admin was silently overwritten by the buildout's build-time
    # placeholder: the site was there and correct, and no password worked.
    rm -f "${INITUSER}"
    SEEDED=1
fi

# Zope <4 has no env interpolation in zope.conf; template the port at start.
# Scoped to the <http-server> block: Zope 2.7 shipped a second <ftp-server>
# block and an unscoped substitution pointed both at the same port, which is a
# fatal bind conflict. 2.10's generated conf has only <http-server>, but the
# scoping costs nothing and keeps the two entrypoints consistent.
sed -i "/^[[:space:]]*<http-server>/,/^[[:space:]]*<\/http-server>/ \
s|^\([[:space:]]*address[[:space:]]\+\)[0-9.:]*[0-9]\+|\1${ZOPE_HTTP_PORT}|" "${CONF}"

# ZEO client, when ZEO_ADDRESS is set; a silent no-op otherwise. Runs AFTER the
# port templating above and before anything opens the database.
/app/configure-zeo.sh "${CONF}" "${INSTANCE_HOME}/var"

# First run against an empty /data: write the emergency user so the admin can
# log in. Once a Data.fs exists, inituser is ignored by Zope anyway; we also
# skip rewriting it so an unset ADMIN_PASSWORD never locks out a restart.
#
# The buildout wrote a placeholder inituser at build time (from the template's
# __PASSWORD__); this replaces it on first start with the real credentials.
# Whether to write inituser at all.
#
# Without ZEO the question is "is /data empty": once a Data.fs exists, Zope has
# its users already. Under ZEO there is no local Data.fs to ask, and answering
# it against a remote storage is not cheap. Writing inituser anyway is NOT
# harmless — [V 2026-08-20] Zope applies it whenever the file EXISTS, without
# checking whether the database already has users — so every client start would
# re-apply it to the shared database and clobber a changed password. Under ZEO
# it is therefore written only when the operator explicitly asks for it by
# supplying ADMIN_PASSWORD, and removed otherwise.
WRITE_INITUSER=0
if [ -n "${ZEO_ADDRESS:-}" ]; then
    if [ -n "${ADMIN_PASSWORD:-}" ]; then
        echo "ZEO_ADDRESS is set and ADMIN_PASSWORD supplied: seeding the emergency user"
        WRITE_INITUSER=1
    else
        rm -f "${INITUSER}"
    fi
elif [ ! -f /data/filestorage/Data.fs ]; then
    WRITE_INITUSER=1
fi

if [ "${WRITE_INITUSER}" = "1" ]; then
    ADMIN_USER="${ADMIN_USER:-admin}"
    if [ -z "${ADMIN_PASSWORD}" ]; then
        echo "WARNING: ADMIN_PASSWORD not set; using 'admin'. Do not expose this container." >&2
        ADMIN_PASSWORD="admin"
    fi
    # [V 2026-08-20] The generated inituser is NOT plaintext — buildout writes
    # "admin:{SHA}<base64>". Rather than reimplement that hash, reuse Zope's own
    # zpasswd.py, exactly as the tarball-era entrypoint reuses
    # ${ZOPE_HOME}/bin/zpasswd.py.
    #
    # Its location is NOT fixed across the buildout era, so it is discovered:
    #   3.1   <instance>/parts/zope2/utilities/zpasswd.py
    #         (plone.recipe.zope2install builds Zope into the instance's parts)
    #   3.2+  /app/Zope-<ver>-py2.4/utilities/zpasswd.py
    #         (the template sets zope-directory, so Zope is shared, one level up)
    ZPASSWD=$(find "$(dirname "${INSTANCE_HOME}")" -path '*/utilities/zpasswd.py' \
        -type f 2>/dev/null | head -1)
    if [ -z "${ZPASSWD}" ]; then
        echo "FATAL: no utilities/zpasswd.py found under $(dirname "${INSTANCE_HOME}")" >&2
        echo "       cannot write the emergency user; refusing to start." >&2
        exit 1
    fi
    "${INSTANCE_HOME}/bin/zopepy" "${ZPASSWD}" \
        -u "${ADMIN_USER}" -p "${ADMIN_PASSWORD}" "${INITUSER}"
    chmod 600 "${INITUSER}"
fi

# -demo images only: apply ADMIN_USER/ADMIN_PASSWORD to the seeded database.
#
# inituser cannot do this. Zope consults it only while CREATING a database, and
# a demo image ships one already made — so without this step the credentials
# baked in at build time would be the only ones that ever worked, and a
# perfectly ordinary `-e ADMIN_PASSWORD=...` would be silently ineffective.
#
# Runs before the exec below, so nothing holds the ZODB lock yet.
if [ "${SEEDED:-0}" = "1" ] && [ -f /app/seed/reset-admin-password.py ]; then
    reset_out=$("${INSTANCE_HOME}/bin/instance" run \
        /app/seed/reset-admin-password.py 2>&1) || true
    # `instance run` does not reliably propagate the script's exit status, so
    # trust the sentinel the script prints and nothing else. Treating a silent
    # failure as success here would hand out an image nobody can log into.
    if ! printf '%s' "${reset_out}" | grep -q 'PASSWORD-RESET-OK'; then
        echo "FATAL: could not apply ADMIN_PASSWORD to the seeded database" >&2
        printf '%s\n' "${reset_out}" >&2
        exit 1
    fi
    printf '%s\n' "${reset_out}" | grep -v 'PASSWORD-RESET-OK' || true
fi

case "$1" in
    start)
        # `fg` runs in the foreground so ZServer is PID 1 and signals reach it.
        exec "${INSTANCE_HOME}/bin/instance" fg
        ;;
    debug)
        exec "${INSTANCE_HOME}/bin/instance" debug
        ;;
    run)
        # Forward EVERY argument. `$2` alone silently drops the script's own
        # arguments, and passes an empty string when no script is named.
        shift
        exec "${INSTANCE_HOME}/bin/instance" run "$@"
        ;;
    upgrade)
        # Deliberately NOT exec'd: the output has to be read.
        #
        # `instance run` does not reliably propagate the script's exit status —
        # the same reason reset-admin-password.py prints a sentinel — so a
        # failed migration exits 0 and looks exactly like a successful one.
        # Verified [V 2026-08-21]: a 3.3 -> 4.0 hop that logged "Migration has
        # failed" still exited 0. Trust the sentinel and nothing else.
        upgrade_out=$("${INSTANCE_HOME}/bin/instance" run /app/upgrade-plone.py 2>&1) || true
        printf '%s\n' "${upgrade_out}" | grep -v 'UPGRADE-OK' || true
        if ! printf '%s' "${upgrade_out}" | grep -q 'UPGRADE-OK'; then
            echo "FATAL: the upgrade did not complete; the database is unchanged" >&2
            exit 1
        fi
        exit 0
        ;;
    *)
        exec "$@"
        ;;
esac
